#
# templates
#

cpu_and_memory_config_for_builds_template: &CPU_AND_MEMORY_CONFIG_FOR_BUILDS_TEMPLATE
  cpu: 4
  memory: 8GB

cpu_and_memory_config_for_tests_template: &CPU_AND_MEMORY_CONFIG_FOR_TESTS_TEMPLATE
  cpu: 1
  memory: 4GB

basic_posix_clean_build_script_template: &BASIC_POSIX_CLEAN_BUILD_SCRIPT_TEMPLATE
  - echo "#### Deleting build and iox-tests-bin dir"
  - if [[ -d "build" ]]; then rm -rf build; fi
  - if [[ -d "iox-tests-bin" ]]; then rm -rf iox-tests-vin; fi
  - echo "#### Running cmake to configure build"
  - cmake -Bbuild -Hiceoryx_meta -DBUILD_STRICT=ON -DBINDING_C=ON -DINTROSPECTION=ON -DEXAMPLES=ON -DBUILD_TEST=ON -DCMAKE_INSTALL_PREFIX=build/install
  - echo "#### Running cmake to build with CIRRUS_CPU = " $CIRRUS_CPU
  - cmake --build build --target install -j $CIRRUS_CPU

test_binaries_for_cache_template: &TEST_BINARIES_FOR_CACHE_TEMPLATE
  - mkdir -p iox-tests-bin
  - mv build/hoofs/test/hoofs_mocktests iox-tests-bin
  - mv build/hoofs/test/hoofs_moduletests iox-tests-bin
  - mv build/dust/test/dust_moduletests iox-tests-bin
  - mv build/posh/test/posh_moduletests iox-tests-bin
  - mv build/posh/test/posh_integrationtests iox-tests-bin
  - mv build/binding_c/test/binding_c_moduletests iox-tests-bin

run_tests_template: &RUN_TESTS_TEMPLATE
  - cd iox-tests-bin
  - ./hoofs_mocktests
  - ./hoofs_moduletests
  - ./dust_moduletests
  - ./posh_moduletests
  - ./posh_integrationtests
  - ./binding_c_moduletests

#
# Pre flight check
#

pre_flight_check_task:
  container:
    dockerfile: tools/ci/docker/ubuntu-22.04
    cpu: 1
    memory: 4GB
  timeout_in: 30m
  clang_format_script: tools/scripts/clang_format.sh check
  check_test_ids_script: tools/scripts/check_test_ids.sh
  check_invalid_characters_script: tools/scripts/check_invalid_characters.sh
  cmake_linter_script: tools/ci/cmake-linter.sh

#
# Ubuntu 22.04 x64 [Extended]
#

task:
  name: Ubuntu 22.04 x64 [Extended:BuildAndPackage]
  depends_on: pre_flight_check
  container:
    dockerfile: tools/ci/docker/ubuntu-22.04
    << : *CPU_AND_MEMORY_CONFIG_FOR_BUILDS_TEMPLATE
  timeout_in: 20m
  test_binaries_cache:
    # TODO do not cache everything
    folder: build
    reupload_on_changes: true
    fingerprint_key: $CIRRUS_OS_ubuntu_22_04_x64_extended_test_binaries_cache
  setup_script:
    - tools/scripts/add_test_users.sh
  build_and_package_script:
    - tools/iceoryx_build_test.sh clean build-strict build-shared binding-c -j $CIRRUS_CPU
    - tools/iceoryx_build_test.sh package -j $CIRRUS_CPU
    - tools/iceoryx_build_test.sh build-strict build-shared binding-c examples build-test test-add-user -j $CIRRUS_CPU
    # TODO: move to separate build
    # - tools/iceoryx_build_test.sh relwithdebinfo out-of-tree examples toml-config-off clean -j $CIRRUS_CPU

task:
  name: Ubuntu 22.04 x64 [Extended:Test]
  depends_on: Ubuntu 22.04 x64 [Extended:BuildAndPackage]
  container:
    dockerfile: tools/ci/docker/ubuntu-22.04
    << : *CPU_AND_MEMORY_CONFIG_FOR_TESTS_TEMPLATE
  timeout_in: 20m
  test_binaries_cache:
    folder: build
    reupload_on_changes: false
    fingerprint_key: $CIRRUS_OS_ubuntu_22_04_x64_extended_test_binaries_cache
  setup_script:
    - tools/scripts/add_test_users.sh
  test_script:
    - tools/iceoryx_build_test.sh no-build test

#
# Ubuntu 22.04 x64 [Basic]
#

task:
  name: Ubuntu 22.04 x64 [Basic:Build]
  depends_on: pre_flight_check
  container:
    dockerfile: tools/ci/docker/ubuntu-22.04
    << : *CPU_AND_MEMORY_CONFIG_FOR_BUILDS_TEMPLATE
  timeout_in: 20m
  test_binaries_cache:
    folder: iox-tests-bin
    reupload_on_changes: true
    fingerprint_key: $CIRRUS_OS_ubuntu_22_04_x64_basic_test_binaries_cache
  build_script:
    << : *BASIC_POSIX_CLEAN_BUILD_SCRIPT_TEMPLATE
  populate_test_binary_folder_script:
    << : *TEST_BINARIES_FOR_CACHE_TEMPLATE

task:
  name: Ubuntu 22.04 x64 [Basic:Test]
  depends_on: Ubuntu 22.04 x64 [Basic:Build]
  container:
    dockerfile: tools/ci/docker/ubuntu-22.04
    << : *CPU_AND_MEMORY_CONFIG_FOR_TESTS_TEMPLATE
  timeout_in: 20m
  test_binaries_cache:
    folder: iox-tests-bin
    reupload_on_changes: false
    fingerprint_key: $CIRRUS_OS_ubuntu_22_04_x64_basic_test_binaries_cache
  test_script:
    << : *RUN_TESTS_TEMPLATE

#
# Ubuntu 22.04 aarch64 [Basic]
#

task:
  name: Ubuntu 22.04 aarch64 [Basic:Build]
  depends_on: pre_flight_check
  arm_container:
    dockerfile: tools/ci/docker/ubuntu-22.04
    << : *CPU_AND_MEMORY_CONFIG_FOR_BUILDS_TEMPLATE
  timeout_in: 20m
  test_binaries_cache:
    folder: iox-tests-bin
    reupload_on_changes: true
    fingerprint_key: $CIRRUS_OS_ubuntu_22_04_aarch64_basic_test_binaries_cache
  setup_script: apt-get update && apt-get install -y g++ cmake git libacl1-dev libncurses5-dev
  build_script:
    << : *BASIC_POSIX_CLEAN_BUILD_SCRIPT_TEMPLATE
  populate_test_binary_folder_script:
    << : *TEST_BINARIES_FOR_CACHE_TEMPLATE

task:
  name: Ubuntu 22.04 aarch64 [Basic:Test]
  depends_on: Ubuntu 22.04 aarch64 [Basic:Build]
  arm_container:
    dockerfile: tools/ci/docker/ubuntu-22.04
    << : *CPU_AND_MEMORY_CONFIG_FOR_TESTS_TEMPLATE
  timeout_in: 20m
  test_binaries_cache:
    folder: iox-tests-bin
    reupload_on_changes: false
    fingerprint_key: $CIRRUS_OS_ubuntu_22_04_aarch64_basic_test_binaries_cache
  env:
    # RouDiEnvironment_test.StartingRouDiTwiceLeadsToError is a death test and causes the CI to hang
    GTEST_FILTER: "-RouDiEnvironment_test.StartingRouDiTwiceLeadsToError"
  test_script:
    << : *RUN_TESTS_TEMPLATE

#
# Arch Linux x64 [Basic]
#

task:
  name: Arch Linux x64 [Basic:Build]
  depends_on: pre_flight_check
  container:
    dockerfile: tools/ci/docker/archlinux-base-devel
    << : *CPU_AND_MEMORY_CONFIG_FOR_BUILDS_TEMPLATE
  timeout_in: 20m
  test_binaries_cache:
    folder: iox-tests-bin
    reupload_on_changes: true
    fingerprint_key: $CIRRUS_OS_archlinux_x64_basic_test_binaries_cache
  env:
    # use clang on archlinux since GCC triggers some compiler warnings which abort the job
    CC: clang
    CXX: clang++
  build_script:
    << : *BASIC_POSIX_CLEAN_BUILD_SCRIPT_TEMPLATE
  populate_test_binary_folder_script:
    << : *TEST_BINARIES_FOR_CACHE_TEMPLATE

task:
  name: Arch Linux x64 [Basic:Test]
  depends_on: Arch Linux x64 [Basic:Build]
  container:
    dockerfile: tools/ci/docker/archlinux-base-devel
    << : *CPU_AND_MEMORY_CONFIG_FOR_TESTS_TEMPLATE
  timeout_in: 20m
  test_binaries_cache:
    folder: iox-tests-bin
    reupload_on_changes: false
    fingerprint_key: $CIRRUS_OS_archlinux_x64_basic_test_binaries_cache
  env:
    # RouDiEnvironment_test.StartingRouDiTwiceLeadsToError is a death test and causes the CI to hang
    GTEST_FILTER: "-RouDiEnvironment_test.StartingRouDiTwiceLeadsToError"
  test_script:
    << : *RUN_TESTS_TEMPLATE

#
# FreeBSD x64 [Basic]
#

task:
  name: FreeBSD 13.2 x64 [Basic:Build]
  depends_on: pre_flight_check
  freebsd_instance:
    image_family: freebsd-13-2
    << : *CPU_AND_MEMORY_CONFIG_FOR_BUILDS_TEMPLATE
  timeout_in: 20m
  test_binaries_cache:
    folder: iox-tests-bin
    reupload_on_changes: true
    fingerprint_key: $CIRRUS_OS_freebsd_test_binaries_cache
  setup_script:
    - pkg install -y cmake git ncurses bash wget
    - ln -s /usr/local/bin/bash /bin/bash
  build_script:
    << : *BASIC_POSIX_CLEAN_BUILD_SCRIPT_TEMPLATE
  populate_test_binary_folder_script:
    << : *TEST_BINARIES_FOR_CACHE_TEMPLATE

task:
  name: FreeBSD 13.2 x64 [Basic:Test]
  depends_on: FreeBSD 13.2 x64 [Basic:Build]
  freebsd_instance:
    image_family: freebsd-13-2
    << : *CPU_AND_MEMORY_CONFIG_FOR_TESTS_TEMPLATE
  timeout_in: 20m
  test_binaries_cache:
    folder: iox-tests-bin
    reupload_on_changes: false
    fingerprint_key: $CIRRUS_OS_freebsd_test_binaries_cache
  setup_script:
    - pkg install -y cmake git ncurses bash wget
    - ln -s /usr/local/bin/bash /bin/bash
  test_script:
    << : *RUN_TESTS_TEMPLATE

#
# macOS aarch64 [Basic]
#

task:
  name: macOS latest aarch64 [Basic:Build]
  depends_on: pre_flight_check
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
    << : *CPU_AND_MEMORY_CONFIG_FOR_BUILDS_TEMPLATE
  timeout_in: 20m
  test_binaries_cache:
    folder: iox-tests-bin
    reupload_on_changes: true
    fingerprint_key: $CIRRUS_OS_macOS_test_binaries_cache
  setup_script:
    - brew install ncurses
  build_script:
    << : *BASIC_POSIX_CLEAN_BUILD_SCRIPT_TEMPLATE
  populate_test_binary_folder_script:
    << : *TEST_BINARIES_FOR_CACHE_TEMPLATE

task:
  name: macOS latest aarch64 [Basic:Test]
  depends_on: macOS latest aarch64 [Basic:Build]
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
    << : *CPU_AND_MEMORY_CONFIG_FOR_TESTS_TEMPLATE
  timeout_in: 20m
  test_binaries_cache:
    folder: iox-tests-bin
    reupload_on_changes: false
    fingerprint_key: $CIRRUS_OS_macOS_test_binaries_cache
  env:
    # No timing tests on macOS
    GTEST_FILTER: "-*TimingTest*"
  test_script:
    << : *RUN_TESTS_TEMPLATE

#
# Windows x64 [Basic]
#

task:
  name: Windows x64 [Basic:Build]
  depends_on: pre_flight_check
  windows_container:
    image: cirrusci/windowsservercore:cmake
    << : *CPU_AND_MEMORY_CONFIG_FOR_BUILDS_TEMPLATE
  timeout_in: 20m
  test_binaries_cache:
    folder: iox-tests-bin
    reupload_on_changes: true
    fingerprint_key: $CIRRUS_OS_Windows_x64_test_binaries_cache
  env:
    CIRRUS_SHELL: powershell
  build_script:
    - echo "#### Deleting build and iox-tests-bin dir"
    - if (Test-Path "build") { Remove-Item "build" -Force -Recurse }
    - if (Test-Path "iox-tests-bin") { Remove-Item "iox-tests-bin" -Force -Recurse }
    - echo "#### Running cmake to configure build"
    - cmake -Bbuild -Hiceoryx_meta -DBINDING_C=ON -DINTROSPECTION=OFF -DEXAMPLES=ON -DBUILD_TEST=ON -DCMAKE_CXX_FLAGS="/MP" -DCMAKE_SYSTEM_VERSION="10.0.18362.0"
    - echo "#### Running cmake to build with CIRRUS_CPU = " $env:CIRRUS_CPU
    - cmake --build build -j $env:CIRRUS_CPU
  populate_test_binary_folder_script:
    - New-Item -ItemType Directory -Force .\iox-tests-bin
    - Move-Item -Path .\build\hoofs\test\Debug\hoofs_mocktests.exe -Destination .\iox-tests-bin\ -Force
    - Move-Item -Path .\build\hoofs\test\Debug\hoofs_moduletests.exe -Destination .\iox-tests-bin\ -Force
    - Move-Item -Path .\build\dust\test\Debug\dust_moduletests.exe -Destination .\iox-tests-bin\ -Force
    - Move-Item -Path .\build\posh\test\Debug\posh_moduletests.exe -Destination .\iox-tests-bin\ -Force
    - Move-Item -Path .\build\posh\test\Debug\posh_integrationtests.exe -Destination .\iox-tests-bin\ -Force
    - Move-Item -Path .\build\binding_c\test\Debug\binding_c_moduletests.exe -Destination .\iox-tests-bin\ -Force

task:
  name: Windows x64 [Basic:Test]
  depends_on: Windows x64 [Basic:Build]
  windows_container:
    image: cirrusci/windowsservercore:cmake
    << : *CPU_AND_MEMORY_CONFIG_FOR_TESTS_TEMPLATE
  timeout_in: 20m
  test_binaries_cache:
    folder: iox-tests-bin
    reupload_on_changes: false
    fingerprint_key: $CIRRUS_OS_Windows_x64_test_binaries_cache
  env:
    CIRRUS_SHELL: powershell
    GTEST_FILTER: "-\
      :*TimingTest*\
      :ChunkHeader_test.ChunkHeaderBinaryCompatibilityCheck\
      :TomlGatewayConfigParserSuiteTest*\
      :IceoryxRoudiApp_test.ConstructorCalledWithArgUniqueIdTwoTimesReturnError\
      :IceoryxRoudiApp_test.ConstructorCalledWithArgVersionSetRunVariableToFalse\
      :ValidTest*\
      :ParseAllMalformedInput*\
      :MePooSegment_test.SharedMemoryFileHandleRightsAfterConstructor\
      :ChunkBuildingBlocks_IntegrationTest.TwoHopsThreeThreadsNoSoFi\
      :BindingC_Runtime_test.RuntimeNameLengthIsOutOfLimit\
      :BindingC_Runtime_test.RuntimeNameIsNullptr"
  test_script:
    - cd iox-tests-bin
    - .\hoofs_mocktests.exe
    - .\hoofs_moduletests.exe
    - .\dust_moduletests.exe
    - .\posh_moduletests.exe
    - .\posh_integrationtests.exe
    - .\binding_c_moduletests.exe
