#
# templates
#

cpu_and_memory_config_for_builds_template: &CPU_AND_MEMORY_CONFIG_FOR_BUILDS_TEMPLATE
  cpu: 4
  memory: 8GB

cpu_and_memory_config_for_tests_template: &CPU_AND_MEMORY_CONFIG_FOR_TESTS_TEMPLATE
  cpu: 1
  memory: 4GB

basic_posix_clean_build_script_template: &BASIC_POSIX_CLEAN_BUILD_SCRIPT_TEMPLATE
  - echo "#### Deleting build dir"
  - if [[ -d "$CIRRUS_WORKING_DIR/build" ]]; then rm -Rf $CIRRUS_WORKING_DIR/build; fi
  - echo "#### Running cmake to configure build"
  - cmake -Bbuild -Hiceoryx_meta -DBUILD_STRICT=ON -DBINDING_C=ON -DINTROSPECTION=ON -DEXAMPLES=ON -DBUILD_TEST=ON -DCMAKE_INSTALL_PREFIX=build/install
  - echo "#### Running cmake to build with CIRRUS_CPU = " $CIRRUS_CPU
  - cmake --build build --target install -- -j $CIRRUS_CPU

test_binaries_folder_template: &TEST_BINARIES_FOLDER_TEMPLATE
  - ./build/hoofs/test
  - ./build/dust/test
  - ./build/posh/test
  - ./build/binding_c/test

run_tests_template: &RUN_TESTS_TEMPLATE
  - cd $CIRRUS_WORKING_DIR/build/hoofs/test
  - ./hoofs_mocktests
  - ./hoofs_moduletests
  - cd $CIRRUS_WORKING_DIR/build/dust/test
  - ./dust_moduletests
  - cd $CIRRUS_WORKING_DIR/build/posh/test
  - ./posh_moduletests
  - ./posh_integrationtests
  - cd $CIRRUS_WORKING_DIR/build/binding_c/test
  - ./binding_c_moduletests

#
# Pre flight check
#

pre_flight_check_task:
  container:
    dockerfile: tools/ci/docker/ubuntu-22.04
    cpu: 1
    memory: 4GB
  timeout_in: 30m
  clang_format_script: tools/scripts/clang_format.sh check
  check_test_ids_script: tools/scripts/check_test_ids.sh
  check_invalid_characters_script: tools/scripts/check_invalid_characters.sh
  cmake_linter_script: tools/ci/cmake-linter.sh

#
# Ubuntu 22.04 x64 [Extended]
#

task:
  name: Ubuntu 22.04 x64 [Extended:BuildAndPackage]
  depends_on: pre_flight_check
  container:
    dockerfile: tools/ci/docker/ubuntu-22.04
    << : *CPU_AND_MEMORY_CONFIG_FOR_BUILDS_TEMPLATE
  timeout_in: 20m
  test_binaries_cache:
    folder: build
    reupload_on_changes: true
    fingerprint_key: $CIRRUS_OS_ubuntu_22_04_x64_extended_test_binaries_cache
  setup_script:
    - tools/scripts/add_test_users.sh
  build_and_package_script:
    - tools/iceoryx_build_test.sh clean build-strict build-shared binding-c -j $CIRRUS_CPU
    - tools/iceoryx_build_test.sh package -j $CIRRUS_CPU
    - tools/iceoryx_build_test.sh build-strict build-shared binding-c examples build-test test-add-user -j $CIRRUS_CPU
    # TODO: move to separate build
    # - tools/iceoryx_build_test.sh relwithdebinfo out-of-tree examples toml-config-off clean -j $CIRRUS_CPU

task:
  name: Ubuntu 22.04 x64 [Extended:Test]
  depends_on: Ubuntu 22.04 x64 [Extended:BuildAndPackage]
  container:
    dockerfile: tools/ci/docker/ubuntu-22.04
    << : *CPU_AND_MEMORY_CONFIG_FOR_TESTS_TEMPLATE
  timeout_in: 20m
  test_binaries_cache:
    folder: build
    reupload_on_changes: false
    fingerprint_key: $CIRRUS_OS_ubuntu_22_04_x64_extended_test_binaries_cache
  setup_script:
    - tools/scripts/add_test_users.sh
  test_script:
    - tools/iceoryx_build_test.sh no-build test

#
# Ubuntu 22.04 x64 [Basic]
#

task:
  name: Ubuntu 22.04 x64 [Basic:Build]
  depends_on: pre_flight_check
  container:
    dockerfile: tools/ci/docker/ubuntu-22.04
    << : *CPU_AND_MEMORY_CONFIG_FOR_BUILDS_TEMPLATE
  timeout_in: 20m
  test_binaries_cache:
    folders:
      << : *TEST_BINARIES_FOLDER_TEMPLATE
    reupload_on_changes: true
    fingerprint_key: $CIRRUS_OS_ubuntu_22_04_x64_basic_test_binaries_cache
  build_script:
    << : *BASIC_POSIX_CLEAN_BUILD_SCRIPT_TEMPLATE

task:
  name: Ubuntu 22.04 x64 [Basic:Test]
  depends_on: Ubuntu 22.04 x64 [Basic:Build]
  container:
    dockerfile: tools/ci/docker/ubuntu-22.04
    << : *CPU_AND_MEMORY_CONFIG_FOR_TESTS_TEMPLATE
  timeout_in: 20m
  test_binaries_cache:
    folders:
      << : *TEST_BINARIES_FOLDER_TEMPLATE
    reupload_on_changes: false
    fingerprint_key: $CIRRUS_OS_ubuntu_22_04_x64_basic_test_binaries_cache
  test_script:
    << : *RUN_TESTS_TEMPLATE

#
# Ubuntu 22.04 aarch64 [Basic]
#

task:
  name: Ubuntu 22.04 aarch64 [Basic:Build]
  depends_on: pre_flight_check
  arm_container:
    dockerfile: tools/ci/docker/ubuntu-22.04
    # image: ubuntu:22.04
    << : *CPU_AND_MEMORY_CONFIG_FOR_BUILDS_TEMPLATE
  timeout_in: 20m
  test_binaries_cache:
    folders:
      << : *TEST_BINARIES_FOLDER_TEMPLATE
    reupload_on_changes: true
    fingerprint_key: $CIRRUS_OS_ubuntu_22_04_aarch64_basic_test_binaries_cache
  setup_script: apt-get update && apt-get install -y g++ cmake git libacl1-dev libncurses5-dev
  build_script:
    << : *BASIC_POSIX_CLEAN_BUILD_SCRIPT_TEMPLATE

task:
  name: Ubuntu 22.04 aarch64 [Basic:Test]
  depends_on: Ubuntu 22.04 aarch64 [Basic:Build]
  arm_container:
    dockerfile: tools/ci/docker/ubuntu-22.04
    # image: ubuntu:22.04
    << : *CPU_AND_MEMORY_CONFIG_FOR_TESTS_TEMPLATE
  timeout_in: 20m
  test_binaries_cache:
    folders:
      << : *TEST_BINARIES_FOLDER_TEMPLATE
    reupload_on_changes: false
    fingerprint_key: $CIRRUS_OS_ubuntu_22_04_aarch64_basic_test_binaries_cache
  test_script:
    << : *RUN_TESTS_TEMPLATE

#
# Arch Linux x64 [Basic]
#

task:
  name: Arch Linux x64 [Basic:Build]
  depends_on: pre_flight_check
  container:
    dockerfile: tools/ci/docker/archlinux-base-devel
    << : *CPU_AND_MEMORY_CONFIG_FOR_BUILDS_TEMPLATE
  timeout_in: 20m
  test_binaries_cache:
    folders:
      << : *TEST_BINARIES_FOLDER_TEMPLATE
    reupload_on_changes: true
    fingerprint_key: $CIRRUS_OS_archlinux_x64_basic_test_binaries_cache
  build_script:
    << : *BASIC_POSIX_CLEAN_BUILD_SCRIPT_TEMPLATE
  test_script:
    << : *RUN_TESTS_TEMPLATE

task:
  name: Arch Linux x64 [Basic:Test]
  depends_on: Arch Linux x64 [Basic:Build]
  container:
    dockerfile: tools/ci/docker/archlinux-base-devel
    << : *CPU_AND_MEMORY_CONFIG_FOR_TESTS_TEMPLATE
  timeout_in: 20m
  test_binaries_cache:
    folders:
      << : *TEST_BINARIES_FOLDER_TEMPLATE
    reupload_on_changes: false
    fingerprint_key: $CIRRUS_OS_archlinux_x64_basic_test_binaries_cache
  test_script:
    << : *RUN_TESTS_TEMPLATE

#
# FreeBSD x64 [Basic]
#

task:
  name: FreeBSD 13.2 x64 [Basic:Build]
  depends_on: pre_flight_check
  freebsd_instance:
    image_family: freebsd-13-2
    << : *CPU_AND_MEMORY_CONFIG_FOR_BUILDS_TEMPLATE
  timeout_in: 20m
  test_binaries_cache:
    folders:
      << : *TEST_BINARIES_FOLDER_TEMPLATE
    reupload_on_changes: true
    fingerprint_key: $CIRRUS_OS_freebsd_test_binaries_cache
  setup_script:
    - pkg install -y cmake git ncurses bash wget
    - ln -s /usr/local/bin/bash /bin/bash
  build_script:
    << : *BASIC_POSIX_CLEAN_BUILD_SCRIPT_TEMPLATE

task:
  name: FreeBSD 13.2 x64 [Basic:Test]
  depends_on: FreeBSD 13.2 x64 [Basic:Build]
  freebsd_instance:
    image_family: freebsd-13-2
    << : *CPU_AND_MEMORY_CONFIG_FOR_TESTS_TEMPLATE
  timeout_in: 20m
  test_binaries_cache:
    folders:
      << : *TEST_BINARIES_FOLDER_TEMPLATE
    reupload_on_changes: false
    fingerprint_key: $CIRRUS_OS_freebsd_test_binaries_cache
  setup_script:
    - pkg install -y cmake git ncurses bash wget
    - ln -s /usr/local/bin/bash /bin/bash
  test_script:
    << : *RUN_TESTS_TEMPLATE

#
# macOS aarch64 [Basic]
#

task:
  name: macOS latest aarch64 [Basic:Build]
  depends_on: pre_flight_check
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
    << : *CPU_AND_MEMORY_CONFIG_FOR_BUILDS_TEMPLATE
  timeout_in: 20m
  test_binaries_cache:
    folder: build   # TEST_BINARIES_FOLDER_TEMPLATE cannot be used since the macOS image has problems with 'folders' instruction
    reupload_on_changes: true
    fingerprint_key: $CIRRUS_OS_macOS_test_binaries_cache
  setup_script:
    - brew install ncurses
  build_script:
    << : *BASIC_POSIX_CLEAN_BUILD_SCRIPT_TEMPLATE

task:
  name: macOS latest aarch64 [Basic:Test]
  depends_on: macOS latest aarch64 [Basic:Build]
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
    << : *CPU_AND_MEMORY_CONFIG_FOR_TESTS_TEMPLATE
  timeout_in: 20m
  test_binaries_cache:
    folder: build   # TEST_BINARIES_FOLDER_TEMPLATE cannot be used since the macOS image has problems with 'folders' instruction
    reupload_on_changes: false
    fingerprint_key: $CIRRUS_OS_macOS_test_binaries_cache
  test_script:
    << : *RUN_TESTS_TEMPLATE

#
# Windows x64 [Basic]
#

task:
  name: Windows x64 [Basic]
  depends_on: pre_flight_check
  windows_container:
    image: kitware:cmake
    << : *CPU_AND_MEMORY_CONFIG_FOR_BUILDS_TEMPLATE
  timeout_in: 20m
  env:
    CIRRUS_SHELL: powershell
  script: tools/ci/build-test-windows.ps1
